opt_in_rules: # some rules are turned off by default, so you need to opt-in
 - empty_collection_literal
 - empty_count
 - empty_string
 - explicit_init
 - unneeded_parentheses_in_closure_argument
 - operator_usage_whitespace

empty_count:
  severity: warning

line_length:
  warning: 400
  error: 450

function_body_length:
   warning: 200

type_body_length:
  warning: 2000
  error: 2000
  
file_length:
  warning: 2000
  error: 3000
  ignore_comment_only_lines: true

identifier_name:
  min_length: 0
  
disabled_rules:  
  - unused_setter_value
  - large_tuple
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - for_where
  - cyclomatic_complexity
  - nesting
  - shorthand_operator
  - redundant_string_enum_value
  - syntactic_sugar
  - compiler_protocol_init
  
excluded:
  - Carthage
  - Pods
  - Package.swift
  - Tests
  - DerivedData
  - .build

reporter: "xcode"
